name: fpl-ml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.*
  - pandas=2.2.*
  - scikit-learn=1.5.*
  - scipy=1.13.*
  - matplotlib=3.9.*
  - requests=2.32.*
  - pulp=2.8.*
  - joblib=1.4.*
  - lightgbm=4.5.*
  - xgboost=2.1.*
  - pip

#old version:
#name: fpl-ml
#channels:
#  - conda-forge
#dependencies:
#  - python=3.11
#  - numpy
#  - pandas
#  - scikit-learn
#  - scipy
#  - matplotlib
#  - requests
#  - pulp
#  - pip
#  - pip:
#      - lightgbm
#      - xgboost